### ISSUE TITLE
Travis-CI error

### ISSUE THREAD

**Issue by neomerx** [neomerx/cors-illuminate#2]
While building on Travis-CI it fails. Can't reproduce locally.

**UPD** Maybe it's Laravel/Travis problem. Other Travis rebuild gave another error (below)

Log from Travis

```
> php artisan clear-compiled
PHP Fatal error:  Call to a member function set() on a non-object in /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 56
PHP Stack trace:
PHP   1. {main}() /home/travis/build/neomerx/limoncello-collins/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/travis/build/neomerx/limoncello-collins/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:98
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:206
PHP   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
```

Another log on for the same source code

```
> php artisan clear-compiled
Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in :
Stack trace:
#0 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct()
#1 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#2 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#3 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Foundation\Application->make()
#4 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass()
#5 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\Container\Container->getDependencies()
#6 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#7 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#8 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(216): Illuminate\Foundation\Application->make()
#9 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(733): {closure}()
#10 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build()
#11 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#12 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Container/Container.php(1157): Illuminate\Foundation\Application->make()
#13 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(245): Illuminate\Container\Container->offsetGet()
#14 /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(102): Illuminate\Foundation\Console\Kernel->reportException()
#15 /home/travis/build/neomerx/limoncello-collins/artisan(36): Illuminate\Foundation\Console\Kernel->handle()
#16 {main}
```

**Comment by neomerx** [comment]
I have commented out the provider and Travis keep failing. Likely unrelated with this project

```
> php artisan clear-compiled
PHP Fatal error:  Call to a member function set() on array in /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 56
PHP Stack trace:
PHP   1. {main}() /home/travis/build/neomerx/limoncello-collins/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/travis/build/neomerx/limoncello-collins/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:98
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:206
PHP   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/travis/build/neomerx/limoncello-collins/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
```

**Comment by neomerx** [comment]
It appeared Laravel didn't liked one of the config files. It was OK to have such file

``` php
return [
    ...
];
```

but not such file

``` php
$config = [
    ...
];

if (...) {
    // do something with $config
}

return $config;
```
